import Head from 'next/head'
import { AppProps } from 'next/app'
import { ThemeProvider } from 'styled-components'
import theme from 'styles/theme'
import { darkTheme } from 'styles/dark'
import GlobalStyle from 'styles/globalstyles'
import { Context, ContextProvider } from 'utils/context'
import { useContext } from 'react'
import { Router } from 'next/router'

interface CustomAppProps extends AppProps {
  router: Router
}

export default function App({ Component, pageProps, router }: CustomAppProps) {
  return (
    <ContextProvider>
      <AppWrapper Component={Component} pageProps={pageProps} router={router} />
    </ContextProvider>
  )
}

function AppWrapper({ Component, pageProps }: AppProps) {
  const { isDarkTheme } = useContext(Context)
  return (
    <ThemeProvider theme={isDarkTheme ? darkTheme : theme}>
      <GlobalStyle />
      <Head>
        <title>Next Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </ThemeProvider>
  )
}
