import Head from 'next/head'
import { GetStaticProps } from 'next'
import { getAllPostsForHome } from '@/graphql/queries/posts'
import { HomeProps } from '@/graphql/types/posts'

export default function Home({ allPosts: { edges } }: HomeProps) {
  const heroPost = edges[0]?.node

  console.log(edges)

  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{heroPost.title}</div>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const allPosts = await getAllPostsForHome()

  return {
    props: { allPosts },
    revalidate: 10
  }
}
